# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 028dae46718eaf59a4f87a3e7bc17acf3f7a411c0c080068ab8b13679e072b4404a6e06d27fd04b790362773331056493633f13fcb53b035ad4065aa12d8042f

test:
  secret_key_base: cf90ad06d6441c220c942b2305ad366f4c19c77de799632d92d7cb473b8a61e02700126f3ca4b0facd53e73509ddd38f2df38de7752b88f73bfe7ed1cbc736e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
